/**
 * 项目演示数据（Dublin 扩展字段，用于开发预览，后续由后端扫描替代）。
 */

import type { Project } from "./types";

const now = Date.now();
const day = 24 * 60 * 60 * 1000;
const nowIso = new Date(now).toISOString();
const toIso = (ms: number) => new Date(ms).toISOString();

/** 演示用项目列表（8 条，阶梯 modified 便于验证排序/搜索） */
export const mockProjects: Project[] = [
  {
    identifier: "urn:uuid:550e8400-e29b-41d4-a716-446655440001",
    title: "哈利·波特与魔法石",
    language: "zh-CN",
    creator: "J.K. 罗琳",
    contributor: null,
    publisher: "人民文学出版社",
    date: "1997-06-26",
    subjects: ["奇幻", "魔法"],
    description: ["哈利·波特在霍格沃茨的第一年冒险。"],
    rights: null,
    source: null,
    relation: null,
    coverage: null,
    created: toIso(now - 0 * day),
    modified: nowIso,
    modifiedMs: now,
    cover: null,
    content: null,
  },
  {
    identifier: "urn:uuid:550e8400-e29b-41d4-a716-446655440002",
    title: "Pride and Prejudice",
    language: "en",
    creator: "Jane Austen",
    contributor: null,
    publisher: "T. Egerton",
    date: "1813-01-28",
    subjects: ["Romance", "Classic"],
    description: ["A romantic novel of manners."],
    rights: null,
    source: null,
    relation: null,
    coverage: null,
    created: toIso(now - 1 * day),
    modified: toIso(now - 1 * day),
    modifiedMs: now - 1 * day,
    cover: null,
    content: null,
  },
  {
    identifier: "urn:uuid:550e8400-e29b-41d4-a716-446655440003",
    title: "人类简史",
    language: "zh-CN",
    creator: "尤瓦尔·赫拉利",
    contributor: null,
    publisher: "中信出版社",
    date: "2011-01-01",
    subjects: ["历史", "科普"],
    description: ["从智人到智神的历史脉络。"],
    rights: null,
    source: null,
    relation: null,
    coverage: null,
    created: toIso(now - 3 * day),
    modified: toIso(now - 3 * day),
    modifiedMs: now - 3 * day,
    cover: null,
    content: null,
  },
  {
    identifier: "urn:uuid:550e8400-e29b-41d4-a716-446655440004",
    title: "Norwegian Wood",
    language: "en",
    creator: "Haruki Murakami",
    contributor: null,
    publisher: "Kodansha",
    date: "1987-09-04",
    subjects: ["Fiction", "Romance"],
    description: ["A nostalgic story of loss and sexuality."],
    rights: null,
    source: null,
    relation: null,
    coverage: null,
    created: toIso(now - 7 * day),
    modified: toIso(now - 7 * day),
    modifiedMs: now - 7 * day,
    cover: null,
    content: null,
  },
  {
    identifier: "urn:uuid:550e8400-e29b-41d4-a716-446655440005",
    title: "ノルウェイの森",
    language: "ja",
    creator: "村上春樹",
    contributor: null,
    publisher: "講談社",
    date: "1987-09-04",
    subjects: ["小説", "恋愛"],
    description: ["喪失とセクシュアリティの物語。"],
    rights: null,
    source: null,
    relation: null,
    coverage: null,
    created: toIso(now - 10 * day),
    modified: toIso(now - 10 * day),
    modifiedMs: now - 10 * day,
    cover: null,
    content: null,
  },
  {
    identifier: "urn:uuid:550e8400-e29b-41d4-a716-446655440006",
    title: "Le Petit Prince",
    language: "fr",
    creator: "Antoine de Saint-Exupéry",
    contributor: null,
    publisher: "Reynal & Hitchcock",
    date: "1943-04-06",
    subjects: ["Conte", "Philosophie"],
    description: ["Un conte poétique et philosophique."],
    rights: null,
    source: null,
    relation: null,
    coverage: null,
    created: toIso(now - 14 * day),
    modified: toIso(now - 14 * day),
    modifiedMs: now - 14 * day,
    cover: null,
    content: null,
  },
  {
    identifier: "urn:uuid:550e8400-e29b-41d4-a716-446655440007",
    title: "三体",
    language: "zh-CN",
    creator: "刘慈欣",
    contributor: null,
    publisher: "重庆出版社",
    date: "2006-01-01",
    subjects: ["科幻", "宇宙"],
    description: ["地球文明与三体文明的碰撞。"],
    rights: null,
    source: null,
    relation: null,
    coverage: null,
    created: toIso(now - 21 * day),
    modified: toIso(now - 21 * day),
    modifiedMs: now - 21 * day,
    cover: null,
    content: null,
  },
  {
    identifier: "urn:uuid:550e8400-e29b-41d4-a716-446655440008",
    title: "To Kill a Mockingbird",
    language: "en",
    creator: "Harper Lee",
    contributor: null,
    publisher: "J. B. Lippincott & Co.",
    date: "1960-07-11",
    subjects: ["Fiction", "Classic"],
    description: ["A novel about racial injustice."],
    rights: null,
    source: null,
    relation: null,
    coverage: null,
    created: toIso(now - 30 * day),
    modified: toIso(now - 30 * day),
    modifiedMs: now - 30 * day,
    cover: null,
    content: null,
  },
];
